<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('reports', function (Blueprint $table) {
            // ตั้งค่า Charset
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';

            $table->id('pk');
            $table->string('ID', 15)->unique();
            $table->string('REG', 1)->nullable();
            $table->string('CWT', 2)->nullable();
            $table->string('AMP', 2)->nullable();
            $table->string('TAM', 2)->nullable();
            $table->string('MUN', 1)->nullable();
            $table->string('EA', 4)->nullable();
            $table->string('VIL', 2)->nullable();
            $table->string('TSIC_R', 5)->nullable();
            $table->string('TSIC_L', 5)->nullable();
            $table->string('SIZE_R', 2)->nullable();
            $table->string('SIZE_L', 2)->nullable();
            $table->string('NO', 5)->nullable();
            $table->string('YR', 2)->nullable();
            $table->string('ENU', 2)->nullable();
            $table->string('TITLE')->nullable();
            $table->string('RANK')->nullable();
            $table->string('FIRSTNAME')->nullable();
            $table->string('LASTNAME')->nullable();
            $table->string('EST_TITLE')->nullable();
            $table->string('EST_NAME')->nullable();
            $table->string('ANSWER', 1)->nullable();;
            $table->string('ADD_NO')->nullable();
            $table->string('BUILDING')->nullable();
            $table->string('ROOM')->nullable();
            $table->string('STREET')->nullable();
            $table->string('BLK')->nullable();
            $table->string('SOI')->nullable();
            $table->string('SUB_DIST')->nullable();
            $table->string('DISTRICT')->nullable();
            $table->string('PROVINCE')->nullable();
            $table->string('POST_CODE', 5)->nullable();
            $table->string('TEL_NO')->nullable();
            $table->string('E_MAIL')->nullable();
            $table->string('WEB_SITE')->nullable();
            $table->string('SOCIAL')->nullable();
            $table->string('TYPE')->nullable();
            $table->string('ADD_NO_1')->nullable();
            $table->string('BUILDING_1')->nullable();
            $table->string('ROOM_1')->nullable();
            $table->string('STREET_1')->nullable();
            $table->string('BLK_1')->nullable();
            $table->string('SOI_1')->nullable();
            $table->string('SUB_DIST_1')->nullable();
            $table->string('DISTRICT_1')->nullable();
            $table->string('PROVINCE_1')->nullable();
            $table->string('POST_CODE_1', 5)->nullable();
            $table->string('TEL_NO_1')->nullable();
            $table->string('E_MAIL_1')->nullable();
            $table->string('WEB_SITE_1')->nullable();
            $table->string('SOCIAL_1')->nullable();
            $table->string('A01', 2)->nullable();
            $table->string('A02', 13)->nullable();
            $table->string('A03', 13)->nullable();
            $table->string('A04', 13)->nullable();
            $table->string('A05')->nullable();
            $table->string('A06', 1)->nullable();
            $table->string('TITLE_2')->nullable();
            $table->string('RANK_2')->nullable();
            $table->string('FIRSTNAME_2')->nullable();
            $table->string('LASTNAME_2')->nullable();
            $table->string('EST_TITLE_2')->nullable();
            $table->string('EST_NAME_2')->nullable();
            $table->string('ADD_NO_2')->nullable();
            $table->string('BUILDING_2')->nullable();
            $table->string('ROOM_2')->nullable();
            $table->string('STREET_2')->nullable();
            $table->string('BLK_2')->nullable();
            $table->string('SOI_2')->nullable();
            $table->string('SUB_DIST_2')->nullable();
            $table->string('DISTRICT_2')->nullable();
            $table->string('PROVINCE_2')->nullable();
            $table->string('POST_CODE_2', 5)->nullable();
            $table->string('TEL_NO_2')->nullable();
            $table->string('E_MAIL_2')->nullable();
            $table->string('WEB_SITE_2')->nullable();
            $table->string('SOCIAL_2')->nullable();
            $table->string('A061')->nullable();
            $table->string('A07', 3)->nullable();
            $table->string('A08', 2)->nullable();
            $table->string('A081')->nullable();
            $table->string('A09', 2)->nullable();
            $table->string('A10', 1)->nullable();
            $table->string('A11')->nullable();
            $table->string('A12', 1)->nullable();
            $table->string('A13', 1)->nullable();
            $table->string('A14', 1)->nullable();
            $table->string('A15', 1)->nullable();
            $table->string('A16', 1)->nullable();
            $table->string('A17', 1)->nullable();
            $table->string('A18')->nullable();
            $table->string('Remarks_01')->nullable();
            $table->string('B01', 4)->nullable();
            $table->string('B02', 4)->nullable();
            $table->string('B03', 4)->nullable();
            $table->string('B04', 4)->nullable();
            $table->string('B05', 4)->nullable();
            $table->string('B06', 4)->nullable();
            $table->string('B07', 4)->nullable();
            $table->string('B08', 4)->nullable();
            $table->string('B09', 4)->nullable();
            $table->string('B10', 4)->nullable();
            $table->string('B11', 4)->nullable();
            $table->string('B12', 4)->nullable();
            $table->string('B13', 4)->nullable();
            $table->string('B14', 4)->nullable();
            $table->string('B15', 4)->nullable();
            $table->string('B16', 4)->nullable();
            $table->string('B17', 4)->nullable();
            $table->string('B18', 4)->nullable();
            $table->string('B19', 1)->nullable();
            $table->string('B20', 2)->nullable();
            $table->string('B21')->nullable();
            $table->string('B22')->nullable();
            $table->string('B23')->nullable();
            $table->string('B24')->nullable();
            $table->string('B25')->nullable();
            $table->string('Remarks_02')->nullable();
            $table->string('C01')->nullable();
            $table->string('C02')->nullable();
            $table->string('C03')->nullable();
            $table->string('C04')->nullable();
            $table->string('C05')->nullable();
            $table->string('C06')->nullable();
            $table->string('C07')->nullable();
            $table->string('C08')->nullable();
            $table->string('C09')->nullable();
            $table->string('C10')->nullable();
            $table->string('C11')->nullable();
            $table->string('C12')->nullable();
            $table->string('C13')->nullable();
            $table->string('C14')->nullable();
            $table->string('C15')->nullable();
            $table->string('C16')->nullable();
            $table->string('C17')->nullable();
            $table->string('C18')->nullable();
            $table->string('C19')->nullable();
            $table->string('C20')->nullable();
            $table->string('C21')->nullable();
            $table->string('C211')->nullable();
            $table->string('C22')->nullable();
            $table->string('Remarks_03')->nullable();
            $table->string('D01')->nullable();
            $table->string('D02')->nullable();
            $table->string('Remarks_04')->nullable();
            $table->string('E01')->nullable();
            $table->string('E02')->nullable();
            $table->string('E03')->nullable();
            $table->string('E04')->nullable();
            $table->string('E05')->nullable();
            $table->string('E06')->nullable();
            $table->string('E07')->nullable();
            $table->string('E08')->nullable();
            $table->string('E09')->nullable();
            $table->string('E10')->nullable();
            $table->string('E11')->nullable();
            $table->string('E12')->nullable();
            $table->string('E121')->nullable();
            $table->string('E13')->nullable();
            $table->string('Remarks_05')->nullable();
            $table->string('F01')->nullable();
            $table->string('F02')->nullable();
            $table->string('F03')->nullable();
            $table->string('F04')->nullable();
            $table->string('F05')->nullable();
            $table->string('F06')->nullable();
            $table->string('F07')->nullable();
            $table->string('F08')->nullable();
            $table->string('F09')->nullable();
            $table->string('F10')->nullable();
            $table->string('F11')->nullable();
            $table->string('F12')->nullable();
            $table->string('F13')->nullable();
            $table->string('F131')->nullable();
            $table->string('F14')->nullable();
            $table->string('F15')->nullable();
            $table->string('F16')->nullable();
            $table->string('F17')->nullable();
            $table->string('Remarks_06')->nullable();
            $table->string('G01', 1)->nullable();
            $table->string('G02', 1)->nullable();
            $table->string('G03', 1)->nullable();
            $table->string('G04', 1)->nullable();
            $table->string('G05', 1)->nullable();
            $table->string('G06', 1)->nullable();
            $table->string('G07', 1)->nullable();
            $table->string('G08', 1)->nullable();
            $table->string('G09', 1)->nullable();
            $table->string('G10', 1)->nullable();
            $table->string('G11', 1)->nullable();
            $table->string('G12', 1)->nullable();
            $table->string('G13', 1)->nullable();
            $table->string('G14', 1)->nullable();
            $table->string('G141')->nullable();
            $table->string('G15', 1)->nullable();
            $table->string('G16', 1)->nullable();
            $table->string('G17', 1)->nullable();
            $table->string('G18', 1)->nullable();
            $table->string('G19', 1)->nullable();
            $table->string('G20', 1)->nullable();
            $table->string('G21', 1)->nullable();
            $table->string('G22', 1)->nullable();
            $table->string('G23', 1)->nullable();
            $table->string('G24', 1)->nullable();
            $table->string('G25', 1)->nullable();
            $table->string('G26', 1)->nullable();
            $table->string('G27', 1)->nullable();
            $table->string('G271')->nullable();
            $table->string('Remarks_07')->nullable();
            $table->string('H01')->nullable();
            $table->string('H02')->nullable();
            $table->string('H03')->nullable();
            $table->string('H04')->nullable();
            // timestamps (created_at, updated_at)
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('reports');
    }
};
